resources:
  - allow-argocd-to-manage.yaml
  - https://github.com/mmorhun/build-service/build-service/config/default?ref=98bd603006ba016e41754e34d7d97f03cb0c3457
  - build-pipeline-selector.yaml
  - monitoring.yaml
# Skip applying the build-service operands (BuildPipelineSelector) while the build-service operator is being installed.
# See more information about this option, here:
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
namespace: build-service
images:
  - name: quay.io/redhat-appstudio/build-service
    newName: quay.io/redhat-appstudio/build-service
    newTag: 1a16c46678a2bd33556387502d080bfd01263881
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
